### ISSUE TITLE
Problems getting overflow mode to work

### ISSUE THREAD

**Issue by catonthekbd** [DeadMor0z/SatisfactoryMods#10]
(most likely user error :) )
with only one receiver set up to overflow mode, and nothing else have the product in their recipies, the transmitter does not transmit anywhere

I have to set up a 2nd rx, or a machine that uses the product before the "overflow" rx starts working so I can ship stuff to one of my sinks

not sure if I want you to fix this, or to add a "sink" mode to the rx/tx instead where the last slot gets sunk if it is full ...

**Comment by DeadMor0z** [comment]
This is by design. Just build another receiver and set it to buffer mode. So it will accumulate product (and will send it to other machines if needed). And when it become full, then overflow receiver will receive this prroduct.
What the point to produce something which is not used anywhere (and not stored for later use)?
